# Generated by Django 6.1.1 on 2026-09-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.AutoField(db_column='M_ID', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='ID', max_length=20, unique=True)),
                ('pwd', models.CharField(db_column='PWD', max_length=20)),
                ('nickname', models.CharField(db_column='NICKNAME', max_length=30)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('p_id', models.AutoField(db_column='P_ID', primary_key=True, serialize=False)),
                ('p_name', models.CharField(db_column='P_NAME', max_length=100)),
                ('p_addr', models.CharField(db_column='P_ADDR', max_length=200)),
                ('p_lat', models.DecimalField(blank=True, db_column='P_LAT', decimal_places=7, max_digits=10, null=True)),
                ('p_lon', models.DecimalField(blank=True, db_column='P_LON', decimal_places=7, max_digits=10, null=True)),
                ('p_kind', models.CharField(db_column='P_KIND', max_length=100)),
            ],
            options={
                'db_table': 'PLACE',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('s_id', models.AutoField(db_column='S_ID', primary_key=True, serialize=False)),
                ('s_day', models.DateField(db_column='S_DAY')),
            ],
            options={
                'db_table': 'SCHEDULE',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(db_column='C_ID', primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_column='C_NAME', max_length=100)),
                ('place', models.ForeignKey(db_column='P_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.place')),
            ],
            options={
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(db_column='PAY_ID', primary_key=True, serialize=False)),
                ('pay_context', models.CharField(db_column='PAY_CONTEXT', max_length=100)),
                ('pay_pay', models.IntegerField(db_column='PAY_PAY')),
                ('schedule', models.ForeignKey(db_column='S_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.schedule')),
            ],
            options={
                'db_table': 'PAY',
            },
        ),
        migrations.CreateModel(
            name='SchedulePlace',
            fields=[
                ('sp_id', models.AutoField(db_column='SP_ID', primary_key=True, serialize=False)),
                ('visit_order', models.IntegerField(db_column='VISIT_ORDER')),
                ('stay_time', models.IntegerField(db_column='STAY_TIME', help_text='체류 시간(분)')),
                ('arrive_time', models.TimeField(db_column='ARRIVE_TIME')),
                ('start_time', models.TimeField(db_column='START_TIME')),
                ('place', models.ForeignKey(db_column='P_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.place')),
                ('schedule', models.ForeignKey(db_column='S_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.schedule')),
            ],
            options={
                'db_table': 'SCHEDULE_PLACES',
                'ordering': ['visit_order'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('t_id', models.AutoField(db_column='T_ID', primary_key=True, serialize=False)),
                ('t_day', models.DateField(blank=True, db_column='T_DAY', null=True)),
                ('t_place', models.CharField(db_column='T_PLACE', max_length=100)),
                ('t_title', models.CharField(db_column='T_TITLE', max_length=100)),
                ('t_way', models.CharField(blank=True, db_column='T_WAY', max_length=30, null=True)),
                ('t_start', models.DateField(db_column='T_START')),
                ('t_end', models.DateField(db_column='T_END')),
                ('member', models.ForeignKey(db_column='M_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.member')),
            ],
            options={
                'db_table': 'TRAVEL',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='travel',
            field=models.ForeignKey(db_column='T_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.travel'),
        ),
        migrations.AddField(
            model_name='place',
            name='travel',
            field=models.ForeignKey(db_column='T_ID', on_delete=django.db.models.deletion.CASCADE, to='sherpaapp.travel'),
        ),
    ]
