# Generated by Django 6.1.1 on 2026-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherpaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pwd',
            field=models.CharField(db_column='PWD', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(db_column='ID', max_length=30),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_context',
            field=models.CharField(db_column='PAY_CONTENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_addr',
            field=models.CharField(db_column='P_ADDR', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleplace',
            name='arrive_time',
            field=models.TimeField(db_column='ARRIVAL_TIME'),
        ),
    ]
